AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/factories/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'app/services/search_service.rb'
  TargetRubyVersion: 3.1.1

Style/Documentation:
  Enabled: false